env_files:
  github_token: ${{ secrets.access_token }}


builds:
- env:
    - CGO_ENABLED=0
  main: .
  goos:
    - linux
    - darwin
    - windows

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

brews:
  - name: oslo
    tap:
      owner: OpenSLO
      name: homebrew-OpenSLO
    folder: Formula
    homepage: https://github.com/OpenSLO/oslo
    install: bin.install "oslo"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com